// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  general: [
    { type: 'doc', id: 'home' },
    { type: 'autogenerated', dirName: 'general' },
  ],
  rank: [
    { type: 'doc', id: 'home' },
    { type: 'autogenerated', dirName: 'rank' },
  ],
  policies: [
    { type: 'doc', id: 'home' },
    { type: 'autogenerated', dirName: 'policies' },
  ],
  moderation: [
    { type: 'doc', id: 'home' },
    { type: 'autogenerated', dirName: 'moderation' },
  ],
};

export default sidebars;
