// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  general: [
    {
      type: 'category',
      label: 'General',
      link: {
        type: 'generated-index',
        title: 'General Overview',
        description: 'All the essentials you need to know about our community.',
        slug: '/general',
      },
      items: [{ type: 'autogenerated', dirName: 'general' }],
    },
  ],
  rank: [
    {
      type: 'category',
      label: 'Ranks',
      link: {
        type: 'generated-index',
        title: 'Ranks Overview',
        description: 'Learn about our rank system and perks.',
        slug: '/rank',
      },
      items: [{ type: 'autogenerated', dirName: 'rank' }],
    },
  ],
  policies: [
    {
      type: 'category',
      label: 'Policies',
      link: {
        type: 'generated-index',
        title: 'Policies & Rules',
        description: 'Read about our terms of service and community guidelines.',
        slug: '/policies',
      },
      items: [{ type: 'autogenerated', dirName: 'policies' }],
    },
  ],
  moderation: [
    {
      type: 'category',
      label: 'Moderation',
      link: {
        type: 'generated-index',
        title: 'Moderation Guidelines',
        description: 'How we keep the community safe and fair.',
        slug: '/moderation',
      },
      items: [{ type: 'autogenerated', dirName: 'moderation' }],
    },
  ],
};

export default sidebars;
